dist: trusty
sudo: false
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
script:
- ./private/autogen
- ./configure
- make
- TERM=dumb make test

# vim:ts=2 sts=2 sw=2 et
