language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update
 - sudo apt-get install -y automake autoconf autoconf-archive
script:
 - ./private/autogen
 - ./configure
 - make
 - TERM=dumb make test
