dist: xenial
language: c
compiler:
- gcc
- clang
addons:
  apt:
    packages:
    - autoconf
    - autoconf-archive
    - automake
    - cppcheck
branches:
  except:
  - appveyor
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- make -C doc/
- make -C doc/ check
- cppcheck --error-exitcode=1 *.c
- ./private/autogen
- ./configure --prefix ~/.local || cat config.log /fail
- make
- TERM=dumb make test
- make install
- cd /
- nonogram --version
- export MANPATH=~/.local/share/man MANWIDTH=80
- man 1 nonogram | grep -A 10 -w NONOGRAM

# vim:ts=2 sts=2 sw=2 et
